<?php

namespace BStrauss\Engine\ViewHelpers;

use FluidTYPO3\Vhs\ViewHelpers\Render\AbstractRenderViewHelper;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3Fluid\Fluid\Core\Compiler\TemplateCompiler;
use TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\NodeInterface;
use TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\TextNode;
use TYPO3Fluid\Fluid\Core\Parser\SyntaxTree\ViewHelperNode;
use TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperInterface;

class RenderViewHelper extends AbstractRenderViewHelper implements ViewHelperInterface {
  /**
   * @var NodeInterface[]
   */
  protected $childNodes = [];

  /**
   * Sets the direct child nodes of the current syntax tree node.
   *
   * @param NodeInterface[] $childNodes
   * @return void
   */
  public function setChildNodes(array $childNodes) {
    $this->childNodes = $childNodes;
  }

  public function initializeArguments() {
    parent::initializeArguments();

    $this->registerArgument('path', 'string', 'Path to the partial file, EXT:myext/... paths supported.', true);
    $this->registerArgument('arguments', 'array', 'Arguments to pass to the partial.', false, []);
  }

  /**
   * @return string
   */
  public function render() {
    $path = GeneralUtility::getFileAbsFileName($this->arguments['path']);
    $renderedSlots = $this->renderSlots();

    if (count($renderedSlots) === 0)
      $renderedSlots['slot-default'] = $this->renderChildren();

    $arguments = array_merge($this->arguments['arguments'], $renderedSlots);

    $view = $this->getPreparedView();
    $view->setTemplatePathAndFilename($path);
    $view->assignMultiple($arguments);

    return $this->renderView($view);
  }

  /**
   * @return array
   */
  private function renderSlots() {
    $renderedSlots = [];

    foreach ($this->childNodes as $childNode) {
      if ($childNode instanceof ViewHelperNode
          && $childNode->getViewHelperClassName() === SlotViewHelper::class
      ) {
        $slotArguments = $childNode->getArguments();

        /** @var TextNode $name */
        $name = $slotArguments['name'];
        $nameString = $name->getText();

        $slotName = "slot-$nameString";

        $renderedSlots[$slotName] = $childNode->evaluate($this->renderingContext);
      }
    }

    return $renderedSlots;
  }

//  public function compile($argumentsName, $closureName, &$initializationPhpCode, ViewHelperNode $node, TemplateCompiler $compiler) {
//    return parent::compile($argumentsName, $closureName, $initializationPhpCode, $node, $compiler); // TODO: Change the autogenerated stub
//  }
}